CourseTracker/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cTracker.urls')), # '' is a path relative to localhost:8000
]

cTracker/urls.py
from django.urls import path
from . import views



app_name = 'cTracker' # to distinguish from other possible apps
urlpatterns = [
    path('', views.home, name='home'), # we have to write a view called home
    path("homepage/courses/", views.courses, name = 'courses'),
    path("homepage/courses/addcourse/", views.addcourse, name = 'addcourses'),
    path("homepage/courses/enroll/", views.enroll, name ='enroll'),
    path("homepage/", views.homepage, name = 'homepage'),


    ]

cTracker/models.py
from django.db import models


# Create your models here.
class Course(models.Model):
    """A class that describes a course"""
    name = models.CharField(max_length=50)
    courseCode = models.CharField(max_length=10)

    def __str__(self):
        """Method to determine what is written when object is printed"""

        string = self.name
        return string

    def get_coursecode(self):
        return self.courseCode

    def get_coursename(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        """Method to display name"""
        return self.name


class Enrolled(models.Model):
    """A class that describes an enrolled course"""
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    semester = models.IntegerField()
    grade = models.FloatField()

    def __str__(self):
        """Method to determine what is written when object is printed"""
        return "enrolled in course"

    def get_grade(self):
        return self.grade

    def get_semester(self):
        return self.semester

    def get_courseID(self):
        return self.course

cTracker/forms.py
from django import forms
from .models import Course, Student, Enrolled


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'courseCode']
        labels = {'name': 'Course Name', 'courseCode': 'Course Code'}


class EnrolledForm(forms.ModelForm):
    class Meta:
        model = Enrolled
        fields = ['student', 'course', 'semester', 'grade']
        labels = {'student': 'Student ID', 'course': 'Course ID', 'semester': 'Semester', 'grade': 'Grade'}

cTracker/views.py
from django.shortcuts import render, redirect

from .models import Student, Course, Enrolled
from .forms import CourseForm, EnrolledForm


# Create your views here.
def home(request):
    """ the homepage of the main app """
    return render(request, 'main/index.html') # we need to create a file index.html


def homepage(request):
    return render(request, 'main/homepage.html')


def courses(request):

    student_id = 1
    student = Student.objects.get(id=student_id)

    enrolleds = student.enrolled_set.all()

    classes= []
    for ele in enrolleds:
        course_id = ele.get_courseID()
        course = Course.objects.get(name=course_id)
        courseName = course.get_coursename()
        courseCode = course.get_coursecode()
        grade = ele.get_grade()
        semester = ele.get_semester()

        classinfo = ClassInfo(courseName, courseCode, grade, semester)

        classes.append(classinfo)

    context = {'enrolled': enrolleds, 'classes': classes}
    return render(request, 'main/courses.html', context)


def addcourse(request):

    if request.method != 'POST':
        form = CourseForm()

    else:
        form = CourseForm(data=request.POST)
        if form.is_valid():

            form.save()
            return redirect('cTracker:courses')

    context = {'form': form}
    return render(request, 'main/new_course.html', context)


def enroll(request):

    if request.method != 'POST':
        form = EnrolledForm()

    else:
        form = EnrolledForm(data=request.POST)
        if form.is_valid():

            form.save()
            return redirect('cTracker:courses')

    context = {'form': form}
    return render(request, 'main/course_enroll.html', context)


def login(request):
    return render(request, 'main/login.html')




class ClassInfo:

    def __init__(self, name, code, grade, semester):
        self.name = name
        self.code = code
        self.grade = grade
        self.semester = semester

    def get_name(self):
        return self.name

    def get_code(self):
        return self.code

    def get_grade(self):
        return self.grade

    def get_semester(self):
        return self.semester

cTracker/templates/main/course_enroll.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Enroll in Course</title>
</head>
<body>
<form action="{% url 'cTracker:enroll' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add Course</button>
</form>
</body>
</html>

cTracker/templates/main/courses.html
<!DOCTYPE html>
<html>
<head>
    <style>
        .header {
            text-align: center;
        }
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        th, td {
            background-color: #96D4D4;
        }
    </style>
</head>
<body>
    <h1 class="header">Your Courses</h1>

    <button id="deleteButton" style="display:none" type="button" onclick="deleteCourse()"> Delete Selected Courses</button>

    <table id="table">
        <tr>
            <th>Course Name</th>
            <th>Course Code</th>
            <th>Semester</th>
            <th>Grade</th>
            <th>Delete Course</th>
        </tr>
        {% for class in classes %}
        <tr>
            <td>{{class.get_name}}</td>
            <td>{{class.get_code}}</td>
            <td>{{class.get_semester}}</td>
            <td>{{class.get_grade}}</td>
            <td><form><input type="checkbox" id="checkbox" onclick="showButton()"></form></td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <p> Link to <a href="enroll">enroll in a course</a>.</p>
    <p> Link to <a href="addcourse">add a new course to the database</a>.</p>
    

    <script>

        function showButton() {
            document.getElementById('deleteButton').style.display = "block";
        }

        function addCourse() {
            //HERE to add course

            addRow()
        }

        function deleteCourse() {
            //HERE to delete course

            deleteRow()
        }

        function addRow() {
            var table = document.getElementById("table").tBodies[0];
            var newRow = table.insertRow();

            var newCellOne = newRow.insertCell();
            var name = document.getElementById("name")
            newCellOne.appendChild(name);

            var newCellTwo = newRow.insertCell();
            var code = document.getElementById("code")
            newCellTwo.appendChild(code);

            var newCellThree = newRow.insertCell();
            var semester = document.getElementById("semester")
            newCellThree.appendChild(semester);

            var newCellFour = newRow.insertCell();
            var grade = document.getElementById("grade")
            newCellFour.appendChild(grade);
        }

        function deleteRow()  {
            var table = document.getElementById("table").tBodies[0];
            var rowCount = table.rows.length;

            for(var i=1; i<rowCount; i++) {
                var row = table.rows[i];
                var chkbox = row.cells[4].getElementsByTagName('input')[0];
                if('checkbox' == chkbox.type && true == chkbox.checked) {
                    table.deleteRow(i);


                }
            }
        }
    </script>
</body>

cTracker/templates/main/homepage.html
<!DOCTYPE html>
<html>
<head>
    <title> Course Tracker </title>
    <style>
        @font-face {
        font-family: Helvetica;
        src: url('Helvetica.ttf');
    }
    .header {
        text-align: center;
    }

    </style>
</head>
<body>
    <h1 class="header">Course Tracker</h1>
    <h4 class = "header">The website that keeps track of your classes</h4>

    <p>
        {% if user.is_authenticated %}
            Welcome {{ user.username }}!
        {% endif %}
    </p>

    {% if user.is_authenticated %}
    <button onclick="window.location.href = 'courses'" type="button"> Continue to Database</button>
    {% else %}
    <button onclick="window.location.href = 'login'" type="button"> Login or Signup</button>
    {% endif %}
    <br>
    <p> Link to <a href="courses">courses page</a>.</p>
</body>
</html>

cTracker/templates/main/index.html
<!DOCTYPE html>
<html>
<head>

</head>
<body>

</body>
</html>

cTracker/templates/main/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1> Login Page </h1>

    <button onclick="window.location.href = 'http://localhost:8000/templates/main/signup.html'">Sign Up</button><br><br>

    <form>
        <label>Username</label><br>
        <input type="text" id="username" name="username"><br>
        <label>Password</label><br>
        <input type="text" id="password" name="password"><br><br>
        <input type="submit" value="Login">
    </form>


</body>
</html>

cTracker/templates/main/new_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Course</title>
</head>
<body>
<form action="{% url 'cTracker:addcourses' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add Course</button>
</form>


</body>
</html>